using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FormUI
{
    class PatchNames
    {
        public static int NO_PATCH = 4096;
        public static int GM_PATCH = 2048;
        public static int PCM_PATCH = 200;
        public static int[] bankstarts = { GM_PATCH, PCM_PATCH, PCM_PATCH + 80, PCM_PATCH + 80 + 100, PCM_PATCH + 80 + 100 + 60, PCM_PATCH + 80 + 100 + 60 + 100 };

        public static string getProgramName(int program)
        {

            if (program == NO_PATCH)
                return "No Patch";
            if ((program & GM_PATCH) > 0)
            {
                program = program & (~GM_PATCH);
                return gmPatch(program);
            }
            else
                return xpPatch(program);
        }
        public static string getProgramName(int bank,int program)
        {
            if (Favorites.IsTriPatch(bank, program))
                return Favorites.GetTriPatchName(bank, program);
            else
                return getProgramName(bankstarts[bank] + program);
        }

        public static string gmPatch(int program)
        {
            if (program< gmpatches.Length)
              return gmpatches[program];
            return "GM Error";
        }

        public static string xpPatch(int program)
        {
            if (program < xppatches.Length)
                return xppatches[program];
            return "XW Error";
        }
        public static readonly string[] xppatches = {
"XW SoloSynth",
"XW SoloSyn 1",
"XW SoloSyn 2",
"XW SoloSyn 3",
"MM Raw Lead",
"XW SoloSyn 4",
"XW SoloSyn 5",
"XW SoloSyn 6",
"XW SoloSyn 7",
"MG Raw Lead",
"XW LeadSynth",
"XW LeadSyn 1",
"XW LeadSyn 2",
"XW LeadSyn 3",
"XW LeadSyn 4",
"XW LeadSyn 5",
"XW LeadSyn 6",
"CZ  RawLead1",
"CZ  RawLead2",
"CZ  RawLead3",
"ChrisMayLead",
"Whistler",
"Theremin Oct",
"SnakeCharmin",
"Ody Raw Lead",
"Gaa-Gaa Saw",
"HiPasfitLead",
"Transistory",
"TrezBandPass",
"AP Raw Lead",
"HiTresMotion",
"Rezonant 5th",
"FuzzyHarmnix",
"SyncOsc Lead",
"OB Raw Lead",
"Harmoniclime",
"WishYouHorn",
"Asian Brass",
"Lucky Square",
"P5 Raw Lead",
"Triangle XMW",
"Woody Lead",
"Xfadly Saw",
"Flutron Lead",
"ND Raw Lead",
"FretlessLead",
"AndYou&Lead",
"SynthitarLed",
"Motion Vox",
"JP Raw Lead",
"ElectroChoir",
"BellSineLead",
"Octrian Lead",
"OctSawCzLead",
"Pinched 4ths",
"Open Fifths",
"OctPulseLead",
"Transistord",
"Poncom Synth",
"DelaySawBass",
"XW SynthBass",
"XW SynBass 1",
"XW SynBass 2",
"XW SynBass 3",
"XW SynBass 4",
"XW SynBass 5",
"XW SynBass 6",
"XW SynBass 7",
"Drama-Kehew",
"TransAmbient",
"RetroSynBass",
"Retro-Bass 1",
"Retro-Bass 2",
"Retro-Bass 3",
"Retro-Bass 4",
"Retro-Bass 5",
"Retro-Bass 6",
"Retro-Bass 7",
"Synth Hit 1",
"Synth Hit 2",
"VirtualWaves",
"WaveNation 1",
"WaveNation 2",
"WaveNation 3",
"WaveNation 4",
"WaveNation 5",
"WaveNation 6",
"ModWheel S&H",
"Sonar Ping",
"DribbleSpace",
"MG KnobSlidr",
"MM KnobSlidr",
"Od KnobSlidr",
"26 KnobSlidr",
"OB KnobSlidr",
"P5 KnobSlidr",
"JP KnobSlidr",
"ND KnobSlidr",
"CZ KnobSlidr",
"Basic&Mic IN",
"XW-PolySynth",
"HEX-PolyOsc",
"HEX-PolyHorn",
"HEX-VeloCity",
"HEX-TouchPad",
"HEX-Splits70",
"AwakenLayer",
"ElectroSplit",
"PaddyPolyPad",
"JupitrianPad",
"Asian Horns",
"DreamyVoxPad",
"GalaxyVoices",
"Streamy Pad",
"Pretty Pad",
"LushnessPoly",
"Underwater",
"WarmPolyPad",
"Poly Square",
"Moody Over",
"Ensemblinas",
"Syn Phonizer",
"Sleep State",
"Dark Backing",
"XFade Factor",
"HoldForRise",
"Evolution",
"Voxy Lady",
"Analogued",
"HEX Poly OSC",
"Arpegginet",
"PolyPopTecno",
"Hells Bells",
"Daydreaming",
"FloySoloPad",
"Ice Castles",
"Hybrid Split",
"Bariss Chirp",
"80s Jamming",
"80s Combo",
"AfricanLayer",
"Ballad Layer",
"QuietlyLayer",
"The Sultan",
"OrchstralHEX",
"Piper Breath",
"Golden Threa",
"Hitbasticata",
"BellScatters",
"ShimmerMeteo",
"DrawbarOrg 1",
"Jazz Organ 1",
"Full Drawbar",
"Perc.Organ 1",
"16â€™+1â€™Organ",
"Soul Organ 1",
"Ovd Organ 1",
"DrawbarOrg 2",
"BlockOrgan 1",
"TheaterOrg 1",
"Jazz Organ 2",
"Soul Organ 2",
"GospelOrgan1",
"ChorusOrgan1",
"Ovd Organ 2",
"BlockOrgan 2",
"DrawbarOrg 3",
"Perc.Organ 2",
"TheaterOrg 2",
"GospelOrgan2",
"Even Organ",
"Flute Organ",
"ChorusOrgan2",
"Ovd Organ 3",
"16â€™Organ",
"Soul Organ 3",
"Perc.Organ 3",
"DrawbarOrg 4",
"Perc.Organ 4",
"Odd Organ",
"Reed Organ 1",
"BlockOrgan 3",
"Ovd Organ 4",
"DrawbarOrg 5",
"GospelOrgan3",
"8â€™+4â€™Organ",
"BlockOrgan 4",
"Reed Organ 2",
"Pure Organ",
"DrawbarOrg 6",
"Perc.Organ 5",
"Phaser Organ",
"TremoloOrgan",
"Deep Cho.Org",
"DelayOrgan 1",
"DelayOrgan 2",
"LfoWah Organ",
"Dist.OrgLead",
"Ring Organ",
"Old Organ",
"StreoGrPiano",
"StroBrtPiano",
"ClassicPiano",
"Rock Piano",
"Modern Piano",
"Dance Piano",
"StringsPiano",
"Piano Pad",
"GM Piano 1",
"GM Piano 2",
"Honky-Tonk",
"GM HonkyTonk",
"Elec.GrPiano",
"E.Grand 80",
"GM Piano 3",
"Harpsichord",
"Coupl.Harpsi",
"GM Harpsi.",
"Elec.Piano",
"FM E.Piano",
"60â€™s E.Piano",
"DynoE.Piano1",
"DynoE.Piano2",
"MelowE.Piano",
"Pop E.Piano",
"Chorus EP",
"Tremolo EP 1",
"Tremolo EP 2",
"Mdn E.Piano",
"Synth-Str.EP",
"GM E.Piano 1",
"GM E.Piano 2",
"VintageClavi",
"Clavi",
"Wah Clavi",
"Dist.Clavi",
"GM Clavi",
"Vibraphone",
"TremoloVibes",
"Marimba",
"Glockenspiel",
"Music Box",
"Tubular Bell",
"Dulcimer",
"GM Celesta",
"GM Glocken.",
"GM Music Box",
"GM Vibraphon",
"GM Marimba",
"GM Xylophone",
"GM TublarBel",
"GM Dulcimer",
"DrawbarOrg 1",
"DrawbarOrg 2",
"Perc.Organ",
"Elec.Organ",
"Jazz Organ",
"Rock Organ",
"Dist.RockOrg",
"70â€™s Organ",
"Full Drawbar",
"Rotary Organ",
"TremoloOrgan",
"Click Organ",
"8â€™Organ",
"Church Organ",
"Chapel Organ",
"Pipe Organ",
"TheaterOrgan",
"Reed Organ",
"Accordion",
"Harmonica",
"GM Organ 1",
"GM Organ 2",
"GM Organ 3",
"GM PipeOrgan",
"GM ReedOrgan",
"GM Accordion",
"GM Harmonica",
"GM Bandoneon",
"Stereo Str.1",
"Stereo Str.2",
"Strings",
"String-Ensm1",
"String-Ensm2",
"BriteStrings",
"Slow Strings",
"Wide Strings",
"Chamber",
"Syn-Strings1",
"Syn-Strings2",
"70â€™s Syn-Str",
"Fast Syn-Str",
"Slow Syn-Str",
"PhaserSynStr",
"Cho.Syn-Str",
"Violin",
"Harp",
"Choir Aahs",
"StringsVoice",
"Voice Doo",
"Synth-Voice1",
"Synth-Voice2",
"VoiceEnsembl",
"Orch.Hit 1",
"Orch.Hit 2",
"GM Violin",
"GM Viola",
"GM Cello",
"GM Contrabas",
"GM Trem.Str.",
"GM Pizzicato",
"GM Harp",
"GM Timpani",
"GM Strings 1",
"GM Strings 2",
"GM SynthStr1",
"GM SynthStr2",
"GM ChoirAahs",
"GM Voice Doo",
"GM Syn-Voice",
"GM Orch.Hit",
"Trumpet",
"Mute Trumpet",
"Trombone",
"Tuba",
"French Horn",
"Stereo Brass",
"Brass",
"BrassSection",
"Synth-Brass1",
"Synth-Brass2",
"WarmSynBrass",
"80â€™sSynBrass",
"A.Syn-Brass",
"Trance Brass",
"GM Trumpet",
"GM Trombone",
"GM Tuba",
"GM MtTrumpet",
"GM Fr.Horn",
"GM Brass",
"GM SynBrass1",
"GM SynBrass2",
"Alto Sax",
"Breathy ASax",
"Tenor Sax",
"Breathy TSax",
"Soprano Sax",
"Baritone Sax",
"Hard A.Sax",
"T.Saxys",
"A.Saxys",
"Clarinet",
"Oboe",
"Bassoon",
"GM Sop.Sax",
"GM Alto Sax",
"GM Tenor Sax",
"GM Bar.Sax",
"GM Oboe",
"GM Eng.Horn",
"GM Bassoon",
"GM Clarinet",
"Flute",
"Piccolo",
"Recorder",
"Pan Flute",
"Bottle Blow",
"Whistle",
"Ocarina",
"Shakuhachi",
"GM Piccolo",
"GM Flute",
"GM Recorder",
"GM Pan Flute",
"GM BotleBlow",
"GM Shakuhach",
"GM Whistle",
"GM Ocarina",
"Nylon Guitar",
"Ambi.NylonGt",
"Steel Guitar",
"Ambi.SteelGt",
"12Str.Guitar",
"Cho.SteelGt",
"Jazz Guitar",
"CleanGuitar1",
"CleanGuitar2",
"Cho.CleanGt",
"Wah E.Guitar",
"Mute Guitar",
"Mute Ovd Gt",
"Crunch E.Gt1",
"Crunch E.Gt2",
"Overdrive Gt",
"DistortionGt",
"More Dist.Gt",
"PowerDist.Gt",
"FlangrDistGt",
"GM Nylon Gt",
"GM Steel Gt",
"GM Jazz Gt",
"GM Clean Gt",
"GM Mute Gt",
"GM Overdrive",
"GM Dist.Gt",
"GM Gt Harm.",
"AcousticBass",
"Ride Bass",
"FingerBass 1",
"FingerBass 2",
"MellowF.Bass",
"Picked Bass",
"RthmPickBass",
"FretlessBass",
"Slap Bass",
"Synth-Bass 1",
"Synth-Bass 2",
"Synth-Bass 3",
"Synth-Bass 4",
"Synth-Bass 5",
"Synth-Bass 6",
"Synth-Bass 7",
"SawSyn-Bass1",
"SawSyn-Bass2",
"Sqr Syn-Bass",
"DigiRockBass",
"Trance Bass",
"Bass & Kick",
"Vocoder Bass",
"SoulSyn-Bass",
"GM AcousBass",
"GM Finger Bs",
"GM Pick Bass",
"GM FretlesBs",
"GM SlapBass1",
"GM SlapBass2",
"GM Syn-Bass1",
"GM Syn-Bass2",
"Square Lead1",
"Square Lead2",
"Square Lead3",
"Square Lead4",
"Sqr Pulse Ld",
"Sine Lead",
"Saw Lead 1",
"Saw Lead 2",
"Saw Lead 3",
"MelowSawLead",
"Pulse Saw Ld",
"SS Lead",
"Slow SqrLead",
"Slow SawLead",
"Seq.Square",
"Seq.Pulse",
"SequenceSine",
"SequenceSaw1",
"SequenceSaw2",
"Trance Lead",
"VA SynthLead",
"VA Synth 1",
"VA Synth 2",
"VA Synth 3",
"VA Synth 4",
"VA Synth 5",
"VA Synth 6",
"VA Syn-SqBs1",
"VA Syn-SqBs2",
"VA Syn-SqBs3",
"VA Syn-SqBs4",
"VA Syn-SqBs5",
"VA Syn-SqBs6",
"Calliope",
"Vent Lead",
"Vent Synth",
"SequenceLead",
"Drop Lead",
"EP Lead",
"Voice Lead",
"Vox Lead",
"Pluck Lead 1",
"Pluck Lead 2",
"Gt SynthLead",
"DblVoiceLead",
"VoiceChoirLd",
"Syn-Voice Ld",
"FifthSawLead",
"FifthSqrLead",
"Fifth Seq.",
"SynthBass+Ld",
"Reed Lead",
"Fret Lead",
"Fantasy 1",
"Fantasy 2",
"New Age",
"New Age Pad",
"Warm Vox",
"Thick Pad",
"Warm Pad",
"Sine Pad",
"Soft Pad",
"Horn Pad",
"Old Tape Pad",
"PolySynth 1",
"PolySynth 2",
"PolySynthPd1",
"PolySynthPd2",
"Poly Saw",
"Heaven",
"SpaceStrPad",
"Chiff Choir",
"Star Voice",
"Square Pad",
"Glass Pad",
"Bottle Pad",
"Ethnic Pad",
"Metal Pad",
"Halo Pad",
"Chorus Pad",
"OrganChoirPd",
"Sweep Choir",
"Rain Drop",
"Wood Pad",
"Space Voice",
"Sound Track",
"XmasBell",
"GlockenChime",
"Vibes Bell",
"Choral Bell",
"Synth-Mallet",
"Celesta Pad",
"Steel Pad",
"BrightBellPd",
"Brightness 1",
"Brightness 2",
"Echo Drop",
"Poly Drop",
"Star Theme",
"Space Pad",
"StandardSet1",
"StandardSet2",
"StandardSet3",
"StandardSet4",
"Room Set",
"Hip-Hop Set",
"Power Set",
"Rock Set",
"Elec.Set",
"Synth Set 1",
"Synth Set 2",
"Trance Set",
"Dance Set 1",
"Dance Set 2",
"Dance Set 3",
"Jazz Set",
"Brush Set",
"OrchestraSet",
"Ethnic Set 1",
"Ethnic Set 2",
"GM Sqr Lead",
"GM Saw Lead",
"GM Calliope",
"GM ChiffLead",
"GM Charang",
"GM VoiceLead",
"GM FifthLead",
"GM Bass+Lead",
"GM Fantasy",
"GM Warm Pad",
"GM PolySynth",
"GM Space Cho",
"GM Bow Glass",
"GM Metal Pad",
"GM Halo Pad",
"GM Sweep Pad",
"GM Rain Drop",
"GM SoundTrak",
"GM Crystal",
"GM Atmosphre",
"GM Brightnes",
"GM Goblins",
"GM Echoes",
"GM SF",
"Er Hu",
"Yang Qin",
"Di Zi",
"Pi Pa",
"Sitar",
"Tanpura",
"Harmonium",
"Santur",
"Kanun",
"Oud",
"Saz",
"Bouzouki",
"GM Sitar",
"GM Banjo",
"GM Shamisen",
"GM Koto",
"GM Thumb Pno",
"GM Bagpipe",
"GM Fiddle",
"GM Shanai",
"GM TinkleBel",
"GM Agogo",
"GM SteelDrum",
"GM WoodBlock",
"GM Taiko",
"GM Melo.Tom",
"GM SynthDrum",
"GM RevCymbal",
"GM GtFrNoise",
"GM BrthNoise",
"GM Seashore",
"GM Bird",
"GM Telephone",
"GM Helicoptr",
"GM Applause",
"GM Gunshot" };

        public static readonly string[] gmpatches = {
         "Grand Piano",
         "Acoustic",
         "Elec. Grand",
         "Honky tonk",
         "E Piano 1",
         "E Piano 2",
         "Harpsichord",
         "Clavinet",
         "Celesta",
         "Glockenspiel",
         "Music Box",
         "Vibraphone",
         "Marimba",
         "Xylophone",
         "Tubular Bells",
         "Dulcimer",
         "Drawbar Organ",
         "Percuss Organ",
         "Rock Organ",
         "Church Organ",
         "Reed Organ",
         "Accordion",
         "Harmonica",
         "Tango Accordion",
         "Acoustic Nylon",
         "Acoustic Steel",
         "Electric Jazz",
         "Electric Clean",
         "Electric Muted",
         "Overdriven",
         "Distortion",
         "Harmonics",
         "Acoustic Bass",
         "Elec. Finger",
         "Elec. Pick",
         "Fretless",
         "Slap Bass 1",
         "Slap Bass 2",
         "Synth Bass 1",
         "Synth Bass 2",
         "Violin",
         "Viola",
         "Cello",
         "Contrabass",
         "Tremolo Strings",
         "Pizzicato Strings",
         "Harp",
         "Timpani",
         "String 1",
         "String 2",
         "SynthString 1",
         "SynthString 2",
         "Choir Aahs",
         "Voice Oohs",
         "Synth Voice",
         "Orchestra Hit",
         "Trumpet",
         "Trombone",
         "Tuba",
         "Muted Trumpet",
         "French Horn",
         "Brass Section",
         "SynthBrass 1",
         "SynthBrass 2",
         "Soprano Sax",
         "Alto Sax",
         "Tenor Sax",
         "Baritone Sax",
         "Oboe",
         "English Horn",
         "Bassoon",
         "Clarinet",
         "Piccolo",
         "Flute",
         "Recorder",
         "Pan Flute",
         "Blown Bottle",
         "Shakuhachi",
         "Whistle",
         "Ocarina",
         "Lead Square",
         "Lead Saw",
         "Calliope",
         "Chiff",
         "Charang",
         "Voice",
         "Fifths",
         "Bass + Lead",
         "New age",
         "Pad Warm",
         "Polysynth",
         "Choir",
         "Bowed",
         "Metallic",
         "Halo",
         "Sweep",
         "FX 1",
         "FX 2",
         "FX 3",
         "FX 4",
         "FX 5",
         "FX 6",
         "FX 7",
         "FX 8",
         "Sitar",
         "Banjo",
         "Shamisen",
         "Koto",
         "Kalimba",
         "Bag pipe",
         "Fiddle",
         "Shanai",
         "Tinkle Bell",
         "Agogo",
         "Steel Drums",
         "Woodblock",
         "Taiko Drum",
         "Melodic Tom",
         "Synth Drum",
         "Reverse Cymbal",
         "Guitar Fret Noise",
         "Breath Noise",
         "Seashore",
         "Bird Tweet",
         "Telephone Ring",
         "Helicopter",
         "Applause",
         "Gunshot"
         };
    }
}
